### ISSUE TITLE
Script `convert.py` is throwing an error

### ISSUE THREAD

**Issue by CrisDamian** [zhaoyuzhi/PyTorch-Special-Pre-trained-Models#2]
I tried converting a pth file and it throws an error like this one. Do I need to install a module or something like this?

```
/[..]/ResNet-50-Gray BN/ResNet50_Gray_epoch70_BN_batchsize64_dict.pth
Traceback (most recent call last):
  File "convert.py", line 9, in <module>
    net = torch.load(name).cuda()
  File "/home/cristian/anaconda3/envs/monodepth/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/cristian/anaconda3/envs/monodepth/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'network_Gray_ResNet'
```

**Comment by CrisDamian** [comment]
Solved this. You need to put `convert.py` in the corresponding source folder for the pth file you are trying to convert. 
Example: I tried to convert `ResNet50_Gray_epoch70_BN_batchsize64_dict.pth` so I have to put it in `ResNet-50 Gray BN/` from the repo.
